export default function FormWrap({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="
    min-h-fit
    h-full
    flex
    items-center
    justify-center
    p-6
    "
    >
      <div
        className="
        max-w-[650px]
      w-full
      flex
      flex-col
      gap-6
      items-center
      shadow-xl
      rounded-md
      p-4
      md:p-8
      "
      >
        {children}
      </div>
    </div>
  );
}
