import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Header from "@/components/home/Header";
import MobileMenu from "@/components/home/MobileMenu";
import CartProvider from "@/providers/CartProvider";
import { Toaster } from "react-hot-toast";
import UserProvider from "@/providers/UserProvider";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "RED OCEAN MARKETING",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-scroll`}
      >
        <Toaster
        // toastOptions={{
        //   style: {
        //     background: "rgb(51 65 85",
        //     color: "#fff",
        //   },
        // }}
        />
        <UserProvider>
          <CartProvider>
            <div className="flex flex-col justify-between min-h-screen gap-8 text-foreground/70 font-[family-name:var(--font-geist-sans)]">
              <Header />
              <main className="pt-20 pb-28">{children}</main>
              <MobileMenu />
            </div>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
